export interface SeedStudent {
  regNumber: string;
  name: string;
  cohort: string;
}

export interface SeedCourse {
  courseCode: string;
  name: string;
  credits: number;
  courseType: string;
}

export const SEED_STUDENTS: SeedStudent[] = [
  { regNumber: 'BSC/48/24', name: "M'tonga Tiyamike", cohort: 'COM1' },
  { regNumber: 'BED/COM/41/24', name: 'Magombo Miriam', cohort: 'COM1' },
  { regNumber: 'BED/COM/22/24', name: 'Magowa Mentry', cohort: 'COM1' },
  { regNumber: 'BSC/COM/35/24', name: 'Magunda Zaithwa', cohort: 'COM1' },
  { regNumber: 'BSC/INF/ME/03/25', name: 'Makawa Genius Samboko', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/02/24', name: 'Makombe Peter', cohort: 'COM1' },
  { regNumber: 'BSC/INF/ME/02/25', name: 'Makuwila Bornwell Nephuwa', cohort: 'COM1' },
  { regNumber: 'BED/COM/44/24', name: 'Makwinja Mirriam', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/19/24', name: 'Makwinja Vincent Lenard', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/04/23', name: 'Malamulo Arthur', cohort: 'COM1' },
  { regNumber: 'BSC/COM/34/24', name: 'Malemia Hawa Salim', cohort: 'COM1' },
  { regNumber: 'BSC/INF/12/24', name: 'Malima Tahirih', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/05/24', name: 'Malisen Mtendere Salvation', cohort: 'COM1' },
  { regNumber: 'BSC/COM/30/24', name: 'Malunga Edith Hazel', cohort: 'COM1' },
  { regNumber: 'BSC/COM/19/24', name: 'Mashonga Blessing Dunga', cohort: 'COM1' },
  { regNumber: 'BSC/INF/03/22', name: 'Matewere Paul', cohort: 'COM1' },
  { regNumber: 'BSC/13/24', name: 'Mateyu Herbert', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/27/24', name: 'Mayenda Deborah', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/31/24', name: 'Mbagalira Evidence Israella', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/16/24', name: 'Mbewe Keneth Chalimbika', cohort: 'COM1' },
  { regNumber: 'BED/COM/43/24', name: 'Mbewe Happiness Mwayi', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/33/24', name: 'Mbonde Chrissy', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/15/24', name: 'Mbosanje Mcdonald', cohort: 'COM1' },
  { regNumber: 'BSC/COM/44/24', name: 'Mchenga Takondwa', cohort: 'COM1' },
  { regNumber: 'BSC/INF/14/24', name: 'Mhango Thanks', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/02/24', name: 'Mhango Julius', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/32/24', name: 'Milekah Joyce Joey', cohort: 'COM1' },
  { regNumber: 'BSC/21/24', name: 'Mkandawire Emmanuel', cohort: 'COM1' },
  { regNumber: 'BED/COM/46/24', name: 'Mkolongo Hlupekile', cohort: 'COM1' },
  { regNumber: 'BSC/COM/24/24', name: 'Mkwanda Banert', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/24/24', name: 'Mlandeni Charles', cohort: 'COM1' },
  { regNumber: 'BSC/INF/32/23', name: 'Mlauzi Zaithwa Yasinta', cohort: 'COM1' },
  { regNumber: 'BSC/INF/07/24', name: 'Mlinde Clint Kaunda', cohort: 'COM1' },
  { regNumber: 'BSC/INF/25/24', name: 'Mlomba Beatrice', cohort: 'COM1' },
  { regNumber: 'BSC/INF/13/24', name: 'Mnyenyembe Kondwani Slynder', cohort: 'COM1' },
  { regNumber: 'BSC/COM/27/24', name: 'Mongola Paul', cohort: 'COM1' },
  { regNumber: 'BED/COM/07/24', name: 'Moyo Innocent', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/30/24', name: 'Mponda Clarissa', cohort: 'COM1' },
  { regNumber: 'BSC/INF/18/24', name: 'Mshani Luka', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/28/24', name: 'Msiska Naomie Tembo', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/16/24', name: 'Msuku Samuel', cohort: 'COM1' },
  { regNumber: 'BSC/COM/20/24', name: 'Muheya Hannah', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/04/24', name: 'Mukhanga Blessings Emmanuel', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/11/24', name: 'Mwachikumba Patrick', cohort: 'COM1' },
  { regNumber: 'BSC/COM/NE/35/24', name: 'Mwadzaangati Steven', cohort: 'COM1' },
  { regNumber: 'BED/COM/13/24', name: 'Mwandira Blessings Trevor', cohort: 'COM1' },
  { regNumber: 'BSC/INF/34/24', name: 'Mwenda Wezzie', cohort: 'COM1' },
  { regNumber: 'BSC/COM/38/24', name: 'Mweso Praise Yamikani', cohort: 'COM1' },
  { regNumber: 'BSC/COM/37/24', name: 'Mwitha Faith', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/31/24', name: 'Mzengo Kettie', cohort: 'COM1' },
  { regNumber: 'BSC/ELE/26/23', name: 'Mziah Alice', cohort: 'COM2' },
  { regNumber: 'BSC/INF/01/24', name: 'Namale Ulemu Frank', cohort: 'COM2' },
  { regNumber: 'BED/COM/25/21', name: 'Namoro Charles', cohort: 'COM2' },
  { regNumber: 'BSC/ELE/12/21', name: 'Nampuluma Martin', cohort: 'COM2' },
  { regNumber: 'BED/COM/37/24', name: 'Nangantani Paul', cohort: 'COM2' },
  { regNumber: 'BSC/COM/04/24', name: 'Nazombe Regina', cohort: 'COM2' },
  { regNumber: 'BSC/INF/19/24', name: 'Ndalahoma Deborah', cohort: 'COM2' },
  { regNumber: 'EFP/BSC/COM/NE/03/24', name: 'Ndovie Lughano Jeremiah', cohort: 'COM2' },
  { regNumber: 'BSC/INF/22/24', name: 'Ndovie Jeremiah', cohort: 'COM2' },
  { regNumber: "BSC/ELE/22/24", name: "Ng'ambi Faith", cohort: 'COM2' },
  { regNumber: 'BSC/COM/31/24', name: 'Ngwira Aulipha', cohort: 'COM2' },
  { regNumber: 'BSC/COM/13/24', name: 'Nkhudzule Allan', cohort: 'COM2' },
  { regNumber: 'BSC/INF/16/24', name: 'Nkolokosa Happy', cohort: 'COM2' },
  { regNumber: 'EFP/BSC/COM/01/24', name: 'Nkosi Ephraim', cohort: 'COM2' },
  { regNumber: 'BED/COM/48/23', name: 'Ntuana Angel', cohort: 'COM2' },
  { regNumber: 'BSC/INF/05/24', name: 'Nyasulu Alex', cohort: 'COM2' },
  { regNumber: 'BSC/ELE/39/23', name: 'Nyirenda Mervis', cohort: 'COM2' },
  { regNumber: 'BSC/INF/03/24', name: 'Nyirenda Blessings', cohort: 'COM2' },
  { regNumber: 'BSC/COM/40/24', name: 'Nyirenda Wanangwa', cohort: 'COM2' },
  { regNumber: 'BSC/COM/NE/03/24', name: 'Nyirenda Wanangwa', cohort: 'COM2' },
  { regNumber: 'BED/COM/14/24', name: 'Nyirongo Chancy Chitimbi', cohort: 'COM2' },
  { regNumber: 'BSC/COM/08/24', name: 'Nyoni Knox', cohort: 'COM2' },
  { regNumber: 'BED/COM/40/24', name: 'Pensulo Chisomo', cohort: 'COM2' },
  { regNumber: 'BSC/INF/28/23', name: 'Phalira Grace Christina', cohort: 'COM2' },
  { regNumber: 'BSC/INF/20/24', name: 'Phiri Praise', cohort: 'COM2' },
  { regNumber: 'BSC/INF/26/24', name: 'Phiri Chitemwa', cohort: 'COM2' },
  { regNumber: 'BED/COM/29/24', name: 'Pondamali Gilbert Davie', cohort: 'COM2' },
  { regNumber: 'EFP/BSC/COM/02/22', name: 'Precious Musole', cohort: 'COM2' },
  { regNumber: 'BSC/INF/17/24', name: 'Sajeni George Dyson Jr.', cohort: 'COM2' },
  { regNumber: 'BSC/COM/12/24', name: 'Saulos Clinton Mkute', cohort: 'COM2' },
  { regNumber: 'BSC/ELE/17/24', name: 'Sava Trevor', cohort: 'COM2' },
  { regNumber: 'BED/COM/25/24', name: 'Simbeye Mwiza Maxwell', cohort: 'COM2' },
  { regNumber: 'BSC/INF/08/23', name: 'Smart Peter Mateyu', cohort: 'COM2' },
  { regNumber: 'BED/COM/20/23', name: 'Soko Qiniso', cohort: 'COM2' },
  { regNumber: 'BSC/INF/08/24', name: 'Solomon Patrick', cohort: 'COM2' },
  { regNumber: 'BSC/COM/NE/30/23', name: 'Solomoni Natasha', cohort: 'COM2' },
  { regNumber: 'BSC/ELE/21/24', name: 'Sululu Mathews', cohort: 'COM2' },
  { regNumber: 'BSC/40/24', name: 'Sumaisi Tendai', cohort: 'COM2' },
  { regNumber: 'BSC/INF/41/25', name: 'Tariq Zymal Fatima', cohort: 'COM2' },
  { regNumber: 'BSC/COM/NE/20/24', name: 'Tembo Thomas Daniel', cohort: 'COM2' },
  { regNumber: 'BSC/27/24', name: 'Temboh Emmanuel', cohort: 'COM2' },
  { regNumber: 'BSC/38/23', name: 'Thonje Thokozani', cohort: 'COM2' },
  { regNumber: 'BSC/ELE/06/24', name: 'Tiki Pemphero', cohort: 'COM2' },
  { regNumber: 'BSC/COM/06/24', name: 'Tsegula Hope Edwin', cohort: 'COM2' },
  { regNumber: 'BSC/COM/02/24', name: 'Tsokalida Nick', cohort: 'COM2' },
  { regNumber: "BED/COM/13/22", name: "Tung'ande Blessings", cohort: 'COM2' },
  { regNumber: 'BSC/INF/10/24', name: 'Umali Amadu B', cohort: 'COM2' },
  { regNumber: 'BSC/COM/15/24', name: 'Vinthenga Blessings', cohort: 'COM2' },
  { regNumber: 'BSC/INF/ME/04/25', name: 'Wasiri Wallace Makande', cohort: 'COM2' },
  { regNumber: 'BSC/06/24', name: 'Yambeni Christian', cohort: 'COM2' },
  { regNumber: 'BED/COM/27/24', name: 'Zaunda Matthews Praise', cohort: 'COM2' },
];

export const SEED_COURSES: SeedCourse[] = [
  { courseCode: 'COM221', name: 'Advanced Computer Programming', credits: 3.0, courseType: 'Regular Course' },
  { courseCode: 'COM222', name: 'Database Systems', credits: 3.0, courseType: 'Regular Course' },
  { courseCode: 'INF221', name: 'Web Design and Development', credits: 3.0, courseType: 'Regular Course' },
  { courseCode: 'INF222', name: 'Enterprise Architecture', credits: 3.0, courseType: 'Regular Course' },
  { courseCode: 'MAT222', name: 'Introduction to Linear Algebra', credits: 3.0, courseType: 'Regular Course' },
];
